### ISSUE TITLE
Cant find log file

### ISSUE THREAD

**Issue by sunjeet95** [akash13singh/lstm_anomaly_thesis#2]
whenever i run the lstm_predictor.py I am getting the following error:

FileNotFoundError: [Errno 2] No such file or directory: '/home/sunjeet/lstm_anomaly_thesis-master/logs/run.log'

Its not able to find the log file. Can anyone help me resolve this.

**Comment by akash13singh** [comment]
Hi @sunjeet95 
Go through the execution instructions in the README file. You need to create the log folder and specify the correct path in the config file.
