### ISSUE TITLE
Space Shuttle

### ISSUE THREAD

**Issue by BehnamTaki** [akash13singh/lstm_anomaly_thesis#7]
Hi Akash!
I've read your report and likewise searched within the files and folders of "lstm_anomaly_thesis". the space shuttle dataset was trained and tested but it was not referenced anywhere in the  thesis. what's the reason?

**Comment by akash13singh** [comment]
Hi Behnam,
I do not remember the specific reason for leaving out the space shuttle dataset. I had originally planned to put the results for many datasets as an appendix to the thesis. For each dataset the model had to be tuned individually. Owing to resource and time constraints ( finishing thesis in time, giving job interviews etc) I managed to do this for a 3-4 datasets only.

**Comment by way-sal** [comment]
Hi Akash,
do you  have any paper or conference for those results,  for example ECG ?

**Comment by BehnamTaki** [comment]
Hi Akash,
sorry,I have another question. what is TRUE data in your resource folder?like train_"true". I compared the"trues" with the original trainset and they weren't the same.

**Comment by akash13singh** [comment]
Yes, there are multiple papers, these are mentioned in the [thesis report] (http://kth.diva-portal.org/smash/record.jsf?pid=diva2%3A1149130&dswid=2431). 
Look at section 3.3.
